// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Example.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class User : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""User"",""namespace"":""Example.Avro"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""friends"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""User""}]},{""name"":""kind"",""type"":{""type"":""enum"",""name"":""Kind"",""namespace"":""Example.Avro"",""symbols"":[""ONE"",""TWO"",""THREE""]}}]}");
		private string _name;
		private IList<Example.Avro.User> _friends;
		private Example.Avro.Kind _kind;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return User._SCHEMA;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public IList<Example.Avro.User> friends
		{
			get
			{
				return this._friends;
			}
			set
			{
				this._friends = value;
			}
		}
		public Example.Avro.Kind kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				this._kind = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.friends;
			case 2: return this.kind;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.friends = (IList<Example.Avro.User>)fieldValue; break;
			case 2: this.kind = (Example.Avro.Kind)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
